### ISSUE TITLE
Plugin fails when target foundry doesn't have public Internet access

### ISSUE THREAD

**Issue by mheath** [pivotal-cf/spring-cloud-dataflow-for-pcf-cli-plugin#6]
When targeting an environment that doesn't have public Internet access, you can an error similar to

```
Attaching shell to dataflow service test in org mheath / space test as admin...
Downloading https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.6.1.RELEASE/spring-cloud-dataflow-shell-1.6.1.RELEASE.jar
FAILED
Downloaded file '/Users/mheath/.cf/spring-cloud-dataflow-for-pcf/cache/spring-cloud-dataflow-shell-1.6.1.RELEASE.jar' checksum does not match supplied value ''
```

This is due to the fact that fetching the SHA hash has been disabled (because it can't get it from Maven anyway.)

**Comment by tichimura-pivotal** [comment]
I found workaround that there should be a file called .cachedata in .cf/spring-cloud-dataflow-for-pcf/cache directory.  
If you edit this file like 
```
{""https://repo.spring.io/libs-release/org/springframework/cloud/spring-cloud-dataflow-shell/1.7.1.RELEASE/spring-cloud-dataflow-shell-1.7.1.RELEASE.jar":"VALUE_OF_SHA_HASH"}
```

 then, you will run this shell.

**Comment by csterwa** [comment]
Workaround is only approach to take at this time. Closing for now.

**Comment by gpsmit** [comment]
Hi, i tried this solution, but i still get the error mentioned by mheath:

Attaching shell to dataflow service data-flow-server in org *** / space backend as ***...
Downloading https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.8.2/spring-cloud-dataflow-shell-2.8.2.jar
FAILED
Downloaded file '~/.cf/spring-cloud-dataflow-for-pcf/cache/spring-cloud-dataflow-shell-2.8.2.jar' checksum does not match supplied value ''


my .cachedata file says:
{"https://repo1.maven.org/maven2/org/springframework/cloud/spring-cloud-dataflow-shell/2.8.2/spring-cloud-dataflow-shell-2.8.2.jar":"fe9882e15dd29230078a4cf30016d6c60bc291f3"}

any help would be great, im kind of lost at the moment
